version: 2
jobs:
   build:
     docker:
       - image: circleci/buildpack-deps:bionic-scm
     steps:
       - run: sudo apt-get install -y --no-install-recommends latexmk chktex texlive-formats-extra texlive-lang-french make
       - checkout
       - run: chktex cv-en.tex cv-fr.tex cv.cls
       - run: make
       - run: mkdir build && cp output/*.pdf *.html build/
       - run: if [ "$CIRCLE_BRANCH" == "master" ]; then bash .circleci/deploy-ghpages.sh build/; fi
       - store_artifacts:
          path: build/