name: Compile Latex and Release PDF

on:
  push:
    branch:
      - master

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        run: sudo apt-get install -y --no-install-recommends latexmk chktex texlive-formats-extra texlive-lang-french make

      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        run: chktex cv-en.tex cv-fr.tex cv.cls

      - name: Get the LaTex files to PDF
        run: make

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            cv-en.pdf
            cv-fr.pdf
          tag_name: "latest"

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull
          git add cv-en.pdf
          git add cv-fr.pdf
          git commit -m "Add built pdf files"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages

